version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_PASSOWORD: root
    ports:
      - "3308:3308"
    volumes:
      - devdojo_data:/var/lib/mysql
volumes:
  devdojo_data: